image: python:3.5.1
   
pipelines:
  default:
    - step:
        script:
          - pip install -U tox
          - pip --version
          - tox --version
          - apt-get update
          - apt-get --force-yes --yes install cmake
          - rm -rf rsyncme
          - git clone --recursive https://bitbucket.org/piotrgregor/rsyncme.git
          - cd rsyncme/src
          - cd ../ && bash ./pip_install_cmocka.sh cmocka && cd src
          - make
          - make test
          - make test-check
